version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/BenningSharp/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
  - package-ecosystem: "nuget"
    directory: "/BenningSharp_Test/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
  - package-ecosystem: "nuget"
    directory: "/BenningSharp_Tests/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
