name: Publish Packages to nuget

on:
  release:
    types: [created]
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.2.2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4.2.0
      with:
        dotnet-version: | 
          8.0
          9.0
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.6.0
      with:
        path: BenningSharp/bin/Release/**/BenningSharp.dll
    - name: Upload to Nuget.org
      run: dotnet nuget push BenningSharp/bin/Release/BenningSharp.*.nupkg --api-key ${{secrets.NUGET_KEY}} -s https://api.nuget.org/v3/index.json